-- ---------------------------------------------------------------------
-- 01_creacion_tablas.sql
-- Avance 1 - Nucleo transaccional (PostgreSQL) - Empresa de cine
-- Responsable: Estefania Paredes Castañeda (tef333)
--
-- Crea las 8 entidades del modelo con llaves primarias, llaves foraneas,
-- restricciones de integridad (UNIQUE, NOT NULL, CHECK, DEFAULT) e indices.
-- Se puede ejecutar varias veces: elimina las tablas y las vuelve a crear.
-- Orden de ejecucion del proyecto: 01 -> 02 -> 03 -> 04 -> 05
-- ---------------------------------------------------------------------

SET client_encoding = 'UTF8';

-- ---------------------------------------------------------------------
-- 0. Limpieza 
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS ventas             CASCADE;
DROP TABLE IF EXISTS contratos          CASCADE;
DROP TABLE IF EXISTS funciones          CASCADE;
DROP TABLE IF EXISTS espectadores       CASCADE;
DROP TABLE IF EXISTS staff              CASCADE;
DROP TABLE IF EXISTS tipos_boleta       CASCADE;
DROP TABLE IF EXISTS actores_directores CASCADE;
DROP TABLE IF EXISTS salas              CASCADE;

-- Nota sobre las llaves primarias: se usa IDENTITY "BY DEFAULT" para que los
-- scripts de datos de prueba puedan insertar IDs explicitos (necesario para
-- coordinar las llaves foraneas entre integrantes). Al final de
-- 02_datos_prueba.sql se reajustan las secuencias.

-- ---------------------------------------------------------------------
-- 1. Tablas sin dependencias
-- ---------------------------------------------------------------------

-- Salas de exhibicion de la empresa
CREATE TABLE salas (
    id_sala     INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(50) NOT NULL,
    capacidad   INTEGER     NOT NULL,
    tipo_sala   VARCHAR(10) NOT NULL DEFAULT '2D',
    estado      VARCHAR(15) NOT NULL DEFAULT 'Activa',
    CONSTRAINT pk_salas           PRIMARY KEY (id_sala),
    CONSTRAINT uq_salas_nombre    UNIQUE (nombre),
    CONSTRAINT ck_salas_capacidad CHECK (capacidad BETWEEN 1 AND 1000),
    CONSTRAINT ck_salas_tipo      CHECK (tipo_sala IN ('2D', '3D', 'IMAX', 'VIP', '4DX')),
    CONSTRAINT ck_salas_estado    CHECK (estado IN ('Activa', 'Mantenimiento', 'Inactiva'))
);

-- Catalogo de tipos de boleta con su precio vigente
CREATE TABLE tipos_boleta (
    id_tipo_boleta INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(40)   NOT NULL,
    descripcion    VARCHAR(150),
    precio         NUMERIC(10,2) NOT NULL,
    activo         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_tipos_boleta     PRIMARY KEY (id_tipo_boleta),
    CONSTRAINT uq_tipos_boleta_nom UNIQUE (nombre),
    CONSTRAINT ck_tipos_boleta_pre CHECK (precio >= 0)
);

-- Actores y directores registrados en la empresa
CREATE TABLE actores_directores (
    id_actor_director INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    nombres           VARCHAR(80)  NOT NULL,
    apellidos         VARCHAR(80)  NOT NULL,
    nombre_artistico  VARCHAR(100),
    tipo              VARCHAR(15)  NOT NULL,
    nacionalidad      VARCHAR(60)  NOT NULL,
    fecha_nacimiento  DATE         NOT NULL,
    correo            VARCHAR(120) NOT NULL,
    telefono          VARCHAR(20),
    fecha_registro    DATE         NOT NULL DEFAULT CURRENT_DATE,
    estado            VARCHAR(10)  NOT NULL DEFAULT 'Activo',
    CONSTRAINT pk_actores_directores PRIMARY KEY (id_actor_director),
    CONSTRAINT uq_actdir_correo      UNIQUE (correo),
    CONSTRAINT uq_actdir_persona     UNIQUE (nombres, apellidos, fecha_nacimiento),
    CONSTRAINT ck_actdir_tipo        CHECK (tipo IN ('Actor', 'Director', 'Actor/Director')),
    CONSTRAINT ck_actdir_estado      CHECK (estado IN ('Activo', 'Inactivo')),
    CONSTRAINT ck_actdir_correo      CHECK (correo ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);

-- Personal de la empresa (taquilla, proyeccion, administracion, etc.)
CREATE TABLE staff (
    id_staff       INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    tipo_documento VARCHAR(3)   NOT NULL DEFAULT 'CC',
    documento      VARCHAR(20)  NOT NULL,
    nombres        VARCHAR(80)  NOT NULL,
    apellidos      VARCHAR(80)  NOT NULL,
    cargo          VARCHAR(25)  NOT NULL,
    correo         VARCHAR(120) NOT NULL,
    telefono       VARCHAR(20),
    fecha_ingreso  DATE         NOT NULL DEFAULT CURRENT_DATE,
    estado         VARCHAR(15)  NOT NULL DEFAULT 'Activo',
    CONSTRAINT pk_staff           PRIMARY KEY (id_staff),
    CONSTRAINT uq_staff_documento UNIQUE (tipo_documento, documento),
    CONSTRAINT uq_staff_correo    UNIQUE (correo),
    CONSTRAINT ck_staff_tipo_doc  CHECK (tipo_documento IN ('CC', 'CE', 'PAS')),
    CONSTRAINT ck_staff_cargo     CHECK (cargo IN ('Administrador', 'Coordinador', 'Taquillero',
                                                   'Proyeccionista', 'Acomodador', 'Servicio al cliente')),
    CONSTRAINT ck_staff_estado    CHECK (estado IN ('Activo', 'Inactivo', 'Vacaciones')),
    CONSTRAINT ck_staff_correo    CHECK (correo ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);

-- Clientes que compran boletas
CREATE TABLE espectadores (
    id_espectador     INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    tipo_documento    VARCHAR(3)   NOT NULL DEFAULT 'CC',
    documento         VARCHAR(20)  NOT NULL,
    nombres           VARCHAR(80)  NOT NULL,
    apellidos         VARCHAR(80)  NOT NULL,
    correo            VARCHAR(120) NOT NULL,
    telefono          VARCHAR(20),
    fecha_nacimiento  DATE         NOT NULL,
    fecha_registro    DATE         NOT NULL DEFAULT CURRENT_DATE,
    puntos_acumulados INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_espectadores     PRIMARY KEY (id_espectador),
    CONSTRAINT uq_espec_documento  UNIQUE (tipo_documento, documento),
    CONSTRAINT uq_espec_correo     UNIQUE (correo),
    CONSTRAINT ck_espec_tipo_doc   CHECK (tipo_documento IN ('CC', 'TI', 'CE', 'PAS')),
    CONSTRAINT ck_espec_puntos     CHECK (puntos_acumulados >= 0),
    CONSTRAINT ck_espec_correo     CHECK (correo ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);

-- ---------------------------------------------------------------------
-- 2. Tablas que dependen de las anteriores
-- ---------------------------------------------------------------------

-- Funciones (proyecciones programadas) en cada sala.
-- Los datos de la pelicula (titulo, genero, clasificacion, duracion) se guardan
-- como ficha de la propia funcion: el alcance fija 8 entidades, sin catalogo de peliculas.
CREATE TABLE funciones (
    id_funcion        INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_sala           INTEGER      NOT NULL,
    titulo_pelicula   VARCHAR(150) NOT NULL,
    genero            VARCHAR(40)  NOT NULL,
    clasificacion     VARCHAR(15)  NOT NULL,
    idioma            VARCHAR(30)  NOT NULL DEFAULT 'Español',
    duracion_min      INTEGER      NOT NULL,
    fecha_hora_inicio TIMESTAMP    NOT NULL,
    estado            VARCHAR(15)  NOT NULL DEFAULT 'Programada',
    CONSTRAINT pk_funciones        PRIMARY KEY (id_funcion),
    CONSTRAINT fk_funciones_sala   FOREIGN KEY (id_sala)
        REFERENCES salas (id_sala) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_funciones_sala_h UNIQUE (id_sala, fecha_hora_inicio),
    CONSTRAINT ck_funciones_clasif CHECK (clasificacion IN ('Todo publico', '+7', '+12', '+15', '+18')),
    CONSTRAINT ck_funciones_durac  CHECK (duracion_min BETWEEN 1 AND 400),
    CONSTRAINT ck_funciones_estado CHECK (estado IN ('Programada', 'En curso', 'Finalizada', 'Cancelada'))
);

-- Contratos con actores/directores para participar en una funcion especial
-- (estreno, conversatorio, presentacion o evento), gestionados por un miembro del staff.
-- fecha_inicio/fecha_fin es la vigencia del contrato.
CREATE TABLE contratos (
    id_contrato       INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_actor_director INTEGER       NOT NULL,
    id_funcion        INTEGER       NOT NULL,
    id_staff          INTEGER       NOT NULL,
    objeto            VARCHAR(200)  NOT NULL,
    tipo_contrato     VARCHAR(20)   NOT NULL,
    fecha_inicio      DATE          NOT NULL,
    fecha_fin         DATE          NOT NULL,
    valor             NUMERIC(12,2) NOT NULL,
    estado            VARCHAR(15)   NOT NULL DEFAULT 'Vigente',
    CONSTRAINT pk_contratos         PRIMARY KEY (id_contrato),
    CONSTRAINT fk_contratos_actdir  FOREIGN KEY (id_actor_director)
        REFERENCES actores_directores (id_actor_director) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_contratos_funcion FOREIGN KEY (id_funcion)
        REFERENCES funciones (id_funcion) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_contratos_staff   FOREIGN KEY (id_staff)
        REFERENCES staff (id_staff) ON UPDATE CASCADE ON DELETE RESTRICT,
    -- Un actor/director no se contrata dos veces para la misma funcion
    CONSTRAINT uq_contratos_actdir_func UNIQUE (id_actor_director, id_funcion),
    CONSTRAINT ck_contratos_tipo    CHECK (tipo_contrato IN ('Estreno', 'Conversatorio', 'Presentacion', 'Evento')),
    CONSTRAINT ck_contratos_fechas  CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_contratos_valor   CHECK (valor > 0),
    CONSTRAINT ck_contratos_estado  CHECK (estado IN ('Vigente', 'Finalizado', 'Cancelado'))
);

-- Ventas de boletas: cada venta es de un tipo de boleta para una funcion.
-- id_staff es NULL cuando la venta se hizo por el canal Online (sin taquillero).
-- El total NO se almacena porque es derivado (cantidad * precio_unitario).
CREATE TABLE ventas (
    id_venta        INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_funcion      INTEGER       NOT NULL,
    id_espectador   INTEGER       NOT NULL,
    id_tipo_boleta  INTEGER       NOT NULL,
    id_staff        INTEGER,
    fecha_venta     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cantidad        INTEGER       NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    canal_venta     VARCHAR(10)   NOT NULL DEFAULT 'Taquilla',
    metodo_pago     VARCHAR(15)   NOT NULL,
    estado          VARCHAR(10)   NOT NULL DEFAULT 'Pagada',
    CONSTRAINT pk_ventas           PRIMARY KEY (id_venta),
    CONSTRAINT fk_ventas_funcion   FOREIGN KEY (id_funcion)
        REFERENCES funciones (id_funcion) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_espec     FOREIGN KEY (id_espectador)
        REFERENCES espectadores (id_espectador) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_tipo      FOREIGN KEY (id_tipo_boleta)
        REFERENCES tipos_boleta (id_tipo_boleta) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_staff     FOREIGN KEY (id_staff)
        REFERENCES staff (id_staff) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_ventas_cantidad  CHECK (cantidad BETWEEN 1 AND 10),
    CONSTRAINT ck_ventas_precio    CHECK (precio_unitario >= 0),
    CONSTRAINT ck_ventas_canal     CHECK (canal_venta IN ('Taquilla', 'Online')),
    CONSTRAINT ck_ventas_metodo    CHECK (metodo_pago IN ('Efectivo', 'Tarjeta', 'Transferencia')),
    CONSTRAINT ck_ventas_estado    CHECK (estado IN ('Pagada', 'Anulada')),
    -- Venta online <=> sin taquillero; en taquilla siempre hay taquillero
    CONSTRAINT ck_ventas_canal_staff  CHECK ((canal_venta = 'Online') = (id_staff IS NULL)),
    -- El efectivo solo aplica en taquilla
    CONSTRAINT ck_ventas_efectivo     CHECK (canal_venta = 'Taquilla' OR metodo_pago <> 'Efectivo')
);

-- ---------------------------------------------------------------------
-- 3. Indices basicos (llaves foraneas y columnas de busqueda frecuente)
--    Las PK y las restricciones UNIQUE ya generan su propio indice.
-- ---------------------------------------------------------------------
CREATE INDEX idx_actdir_apellidos     ON actores_directores (apellidos, nombres);
CREATE INDEX idx_staff_cargo          ON staff (cargo);
CREATE INDEX idx_espec_apellidos      ON espectadores (apellidos, nombres);

CREATE INDEX idx_contratos_actdir     ON contratos (id_actor_director);
CREATE INDEX idx_contratos_funcion    ON contratos (id_funcion);
CREATE INDEX idx_contratos_staff      ON contratos (id_staff);
CREATE INDEX idx_contratos_est_fin    ON contratos (estado, fecha_fin);

CREATE INDEX idx_funciones_inicio     ON funciones (fecha_hora_inicio);
CREATE INDEX idx_funciones_titulo     ON funciones (titulo_pelicula);

CREATE INDEX idx_ventas_funcion       ON ventas (id_funcion);
CREATE INDEX idx_ventas_espectador    ON ventas (id_espectador);
CREATE INDEX idx_ventas_tipo_boleta   ON ventas (id_tipo_boleta);
CREATE INDEX idx_ventas_staff         ON ventas (id_staff);
CREATE INDEX idx_ventas_fecha         ON ventas (fecha_venta);

-- ---------------------------------------------------------------------
-- 4. Comentarios de documentacion
-- ---------------------------------------------------------------------
COMMENT ON TABLE salas              IS 'Salas de exhibicion con su capacidad (aforo) y tipo de proyeccion';
COMMENT ON TABLE tipos_boleta       IS 'Catalogo de tipos de boleta y precio vigente';
COMMENT ON TABLE actores_directores IS 'Actores y directores registrados en la empresa';
COMMENT ON TABLE staff              IS 'Personal de la empresa; los taquilleros registran ventas y administradores/coordinadores gestionan contratos';
COMMENT ON TABLE espectadores       IS 'Clientes que compran boletas, con puntos de fidelizacion';
COMMENT ON TABLE contratos          IS 'Contratos con actores/directores para participar en una funcion, gestionados por un miembro del staff';
COMMENT ON TABLE funciones          IS 'Proyecciones programadas en una sala; la hora de fin se deriva de inicio + duracion';
COMMENT ON TABLE ventas             IS 'Ventas de boletas; total = cantidad * precio_unitario (derivado, no almacenado)';

-- ---------------------------------------------------------------------
-- 5. Verificacion: tablas creadas
-- ---------------------------------------------------------------------
SELECT table_name AS tabla,
       (SELECT COUNT(*) FROM information_schema.columns c
         WHERE c.table_schema = t.table_schema AND c.table_name = t.table_name) AS columnas
FROM information_schema.tables t
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;
